from gym.envs.registration import register

register(
    id='GymnomeAssembly_25_10_8-v1',
    entry_point='gymnome_assembly.envs:Dataset01v1',
)
register(
    id='GymnomeAssembly_25_10_10-v1',
    entry_point='gymnome_assembly.envs:Dataset02v1',
)
register(
    id='GymnomeAssembly_25_10_15-v1',
    entry_point='gymnome_assembly.envs:Dataset03v1',
)
register(
    id='GymnomeAssembly_50_10_8-v1',
    entry_point='gymnome_assembly.envs:Dataset04v1',
)
register(
    id='GymnomeAssembly_50_10_10-v1',
    entry_point='gymnome_assembly.envs:Dataset05v1',
)
register(
    id='GymnomeAssembly_50_10_15-v1',
    entry_point='gymnome_assembly.envs:Dataset06v1',
)
register(
    id='GymnomeAssembly_25_20_8-v1',
    entry_point='gymnome_assembly.envs:Dataset07v1',
)
register(
    id='GymnomeAssembly_25_20_10-v1',
    entry_point='gymnome_assembly.envs:Dataset08v1',
)
register(
    id='GymnomeAssembly_25_20_15-v1',
    entry_point='gymnome_assembly.envs:Dataset09v1',
)
register(
    id='GymnomeAssembly_50_20_8-v1',
    entry_point='gymnome_assembly.envs:Dataset10v1',
)
register(
    id='GymnomeAssembly_50_20_10-v1',
    entry_point='gymnome_assembly.envs:Dataset11v1',
)
register(
    id='GymnomeAssembly_50_20_15-v1',
    entry_point='gymnome_assembly.envs:Dataset12v1',
)
register(
    id='GymnomeAssembly_25_30_8-v1',
    entry_point='gymnome_assembly.envs:Dataset13v1',
)
register(
    id='GymnomeAssembly_25_30_10-v1',
    entry_point='gymnome_assembly.envs:Dataset14v1',
)
register(
    id='GymnomeAssembly_25_30_15-v1',
    entry_point='gymnome_assembly.envs:Dataset15v1',
)
register(
    id='GymnomeAssembly_50_30_8-v1',
    entry_point='gymnome_assembly.envs:Dataset16v1',
)
register(
    id='GymnomeAssembly_50_30_10-v1',
    entry_point='gymnome_assembly.envs:Dataset17v1',
)
register(
    id='GymnomeAssembly_50_30_15-v1',
    entry_point='gymnome_assembly.envs:Dataset18v1',
)
register(
    id='GymnomeAssembly_381_20_75-v1',
    entry_point='gymnome_assembly.envs:Dataset19v1',
)
register(
    id='GymnomeAssembly_567_30_75-v1',
    entry_point='gymnome_assembly.envs:Dataset20v1',
)
register(
    id='GymnomeAssembly_726_40_75-v1',
    entry_point='gymnome_assembly.envs:Dataset21v1',
)
register(
    id='GymnomeAssembly_930_50_75-v1',
    entry_point='gymnome_assembly.envs:Dataset22v1',
)
register(
    id='GymnomeAssembly_4224_230_75-v1',
    entry_point='gymnome_assembly.envs:Dataset23v1',
)
register(
    id='GymnomeAssembly_25_10_8-v2',
    entry_point='gymnome_assembly.envs:Dataset01v2',
)
register(
    id='GymnomeAssembly_25_10_10-v2',
    entry_point='gymnome_assembly.envs:Dataset02v2',
)
register(
    id='GymnomeAssembly_25_10_15-v2',
    entry_point='gymnome_assembly.envs:Dataset03v2',
)
register(
    id='GymnomeAssembly_50_10_8-v2',
    entry_point='gymnome_assembly.envs:Dataset04v2',
)
register(
    id='GymnomeAssembly_50_10_10-v2',
    entry_point='gymnome_assembly.envs:Dataset05v2',
)
register(
    id='GymnomeAssembly_50_10_15-v2',
    entry_point='gymnome_assembly.envs:Dataset06v2',
)
register(
    id='GymnomeAssembly_25_20_8-v2',
    entry_point='gymnome_assembly.envs:Dataset07v2',
)
register(
    id='GymnomeAssembly_25_20_10-v2',
    entry_point='gymnome_assembly.envs:Dataset08v2',
)
register(
    id='GymnomeAssembly_25_20_15-v2',
    entry_point='gymnome_assembly.envs:Dataset09v2',
)
register(
    id='GymnomeAssembly_50_20_8-v2',
    entry_point='gymnome_assembly.envs:Dataset10v2',
)
register(
    id='GymnomeAssembly_50_20_10-v2',
    entry_point='gymnome_assembly.envs:Dataset11v2',
)
register(
    id='GymnomeAssembly_50_20_15-v2',
    entry_point='gymnome_assembly.envs:Dataset12v2',
)
register(
    id='GymnomeAssembly_25_30_8-v2',
    entry_point='gymnome_assembly.envs:Dataset13v2',
)
register(
    id='GymnomeAssembly_25_30_10-v2',
    entry_point='gymnome_assembly.envs:Dataset14v2',
)
register(
    id='GymnomeAssembly_25_30_15-v2',
    entry_point='gymnome_assembly.envs:Dataset15v2',
)
register(
    id='GymnomeAssembly_50_30_8-v2',
    entry_point='gymnome_assembly.envs:Dataset16v2',
)
register(
    id='GymnomeAssembly_50_30_10-v2',
    entry_point='gymnome_assembly.envs:Dataset17v2',
)
register(
    id='GymnomeAssembly_50_30_15-v2',
    entry_point='gymnome_assembly.envs:Dataset18v2',
)
register(
    id='GymnomeAssembly_381_20_75-v2',
    entry_point='gymnome_assembly.envs:Dataset19v2',
)
register(
    id='GymnomeAssembly_567_30_75-v2',
    entry_point='gymnome_assembly.envs:Dataset20v2',
)
register(
    id='GymnomeAssembly_726_40_75-v2',
    entry_point='gymnome_assembly.envs:Dataset21v2',
)
register(
    id='GymnomeAssembly_930_50_75-v2',
    entry_point='gymnome_assembly.envs:Dataset22v2',
)
register(
    id='GymnomeAssembly_4224_230_75-v2',
    entry_point='gymnome_assembly.envs:Dataset23v2',
)